import pathlib

ROBOT_NAME = 'gary'

DOCKER_REPOSITORY = 'unlimitedrobotics'
DOCKER_IMAGE = ROBOT_NAME

# DOCKER IMAGES

IMAGE_NAME_TEMPLATE = (
        f'{DOCKER_REPOSITORY}/{DOCKER_IMAGE}'
        '.{platform}.{repo}.{component}:{version}'
    )

# DIRECTORIES

ROBOT_BASE_PATH = pathlib.Path('/robot')
ROBOT_COMMANDS_PATH = ROBOT_BASE_PATH / 'commands'
ROBOT_GENERIC_STATIC_DATA_PATH = ROBOT_BASE_PATH / 'generic_static_data'
ROBOT_GENERIC_PERSISTENT_DATA_PATH = ROBOT_BASE_PATH / 'generic_persistent_data'
ROBOT_COMPONENT_STATIC_DATA_PATH = ROBOT_BASE_PATH / 'component_static_data'
ROBOT_COMPONENT_PERSISTENT_DATA_PATH = ROBOT_BASE_PATH / 'component_persistent_data'
ROBOT_PROFILE_STATIC_DATA_PATH = ROBOT_BASE_PATH / 'profile_static_data'
ROBOT_CONFIG_PATH = ROBOT_BASE_PATH / 'config'
ROBOT_BUILD_PATH = ROBOT_BASE_PATH / 'build'
ROBOT_SRC_PATH = ROBOT_BASE_PATH / 'src'
ROBOT_ROS_PKGS_PATH = ROBOT_SRC_PATH / 'ros_pkgs'

# ENVIRONMENT VARIABLES

ENV_CONFIG_PATH = 'ROBOT_CONFIGURATION_PATH'
