#!/usr/bin/python3

import argparse
from robotdevenv.deploy import RobotDevDeploy


def deploy_repository():

    print()
    print('🤖🤖 UR ROBOT DEVELOPMENT ENVIRONMENT 🤖🤖')
    print(f'  🦾 Deploy command 🦿')
    print()

    parser: argparse = argparse.ArgumentParser()
    deploy: RobotDevDeploy = RobotDevDeploy(parser)
    deploy.deploy_repository()


if __name__ == '__main__':
    deploy_repository()
