#!/usr/bin/python3

import argparse
from robotdevenv.managed_main_execution import managed_main_execution
from robotdevenv.deploy import RobotDevDeploy


def deploy_repository():

    print()
    print('🤖🤖 UR ROBOT DEVELOPMENT ENVIRONMENT 🤖🤖')
    print(f'  🦾 Deploy command 🦿')
    print()

    parser: argparse = argparse.ArgumentParser()
    robot_dev_deploy: RobotDevDeploy = RobotDevDeploy(parser)
    robot_dev_deploy.deploy_repository()


if __name__ == '__main__':
    managed_main_execution(deploy_repository)
