gary_camera_chest:
    parent_link: 'base_link'
    child_link:  'gary_camera_chest_color_optical_frame'
    translation: [0.0, 0.0, 1.46]
    rotation:    [-1.5708, 0.0, -1.5708]
    
gary_camera_nav_bottom:
    parent_link: 'base_link'
    child_link:  'gary_camera_nav_bottom_link'
    translation: [0.14698, 0.0, 0.809]
    rotation:    [0.0, 0.0, 0.0]

gary_camera_nav_top:
    parent_link: 'base_link'
    child_link:  'gary_camera_nav_top_link'
    translation: [0.084, -0.02, 1.260]
    rotation:    [0.0, 0.8465, 0.0]

gary_camera_cv_top:
    parent_link: 'base_link'
    child_link:  'gary_camera_cv_top_link'
    translation: [0.14698, 0.0, 0.809]
    rotation:    [0.0, 0.0, 0.0]

gary_camera_back:
    parent_link: 'base_link'
    child_link:  'gary_camera_back_link'
    translation: [0.0, 0.0, 1.46]
    rotation:    [0.0, 0.0, 0.0]
